/* tslint:disable */
/* eslint-disable */
/**
 * Bactic
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Athlete } from './Athlete';
import {
    AthleteFromJSON,
    AthleteFromJSONTyped,
    AthleteToJSON,
} from './Athlete';

/**
 * 
 * @export
 * @interface AthleteSummary
 */
export interface AthleteSummary {
    /**
     * 
     * @type {Athlete}
     * @memberof AthleteSummary
     */
    athlete?: Athlete;
    /**
     * 
     * @type {number}
     * @memberof AthleteSummary
     */
    zscore?: number;
}

/**
 * Check if a given object implements the AthleteSummary interface.
 */
export function instanceOfAthleteSummary(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AthleteSummaryFromJSON(json: any): AthleteSummary {
    return AthleteSummaryFromJSONTyped(json, false);
}

export function AthleteSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AthleteSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'athlete': !exists(json, 'athlete') ? undefined : AthleteFromJSON(json['athlete']),
        'zscore': !exists(json, 'zscore') ? undefined : json['zscore'],
    };
}

export function AthleteSummaryToJSON(value?: AthleteSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'athlete': AthleteToJSON(value.athlete),
        'zscore': value.zscore,
    };
}

