/* tslint:disable */
/* eslint-disable */
/**
 * Bactic
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Athlete
 */
export interface Athlete {
    /**
     * 
     * @type {string}
     * @memberof Athlete
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Athlete
     */
    id?: number;
}

/**
 * Check if a given object implements the Athlete interface.
 */
export function instanceOfAthlete(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AthleteFromJSON(json: any): Athlete {
    return AthleteFromJSONTyped(json, false);
}

export function AthleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Athlete {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function AthleteToJSON(value?: Athlete | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'id': value.id,
    };
}

