/* tslint:disable */
/* eslint-disable */
/**
 * Bactic
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Event = {
    _100m: '100m',
    _200m: '200m',
    _1500m: '1500m',
    _5000m: '5000m'
} as const;
export type Event = typeof Event[keyof typeof Event];


export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    return json as Event;
}

export function EventToJSON(value?: Event | null): any {
    return value as any;
}

