/* tslint:disable */
/* eslint-disable */
/**
 * Bactic
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchItem
 */
export interface SearchItem {
    /**
     * 
     * @type {string}
     * @memberof SearchItem
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SearchItem
     */
    id: number;
}

/**
 * Check if a given object implements the SearchItem interface.
 */
export function instanceOfSearchItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function SearchItemFromJSON(json: any): SearchItem {
    return SearchItemFromJSONTyped(json, false);
}

export function SearchItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
    };
}

export function SearchItemToJSON(value?: SearchItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'id': value.id,
    };
}

