/* tslint:disable */
/* eslint-disable */
/**
 * Bactic
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StatsTimeseriesGet200ResponseDataInner } from './StatsTimeseriesGet200ResponseDataInner';
import {
    StatsTimeseriesGet200ResponseDataInnerFromJSON,
    StatsTimeseriesGet200ResponseDataInnerFromJSONTyped,
    StatsTimeseriesGet200ResponseDataInnerToJSON,
} from './StatsTimeseriesGet200ResponseDataInner';

/**
 * 
 * @export
 * @interface StatsTimeseriesGet200Response
 */
export interface StatsTimeseriesGet200Response {
    /**
     * 
     * @type {Array<StatsTimeseriesGet200ResponseDataInner>}
     * @memberof StatsTimeseriesGet200Response
     */
    data: Array<StatsTimeseriesGet200ResponseDataInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof StatsTimeseriesGet200Response
     */
    axis: Array<string>;
}

/**
 * Check if a given object implements the StatsTimeseriesGet200Response interface.
 */
export function instanceOfStatsTimeseriesGet200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "axis" in value;

    return isInstance;
}

export function StatsTimeseriesGet200ResponseFromJSON(json: any): StatsTimeseriesGet200Response {
    return StatsTimeseriesGet200ResponseFromJSONTyped(json, false);
}

export function StatsTimeseriesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatsTimeseriesGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StatsTimeseriesGet200ResponseDataInnerFromJSON)),
        'axis': json['axis'],
    };
}

export function StatsTimeseriesGet200ResponseToJSON(value?: StatsTimeseriesGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(StatsTimeseriesGet200ResponseDataInnerToJSON)),
        'axis': value.axis,
    };
}

