/* tslint:disable */
/* eslint-disable */
/**
 * Bactic
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatsTimeseriesGet200ResponseDataInner
 */
export interface StatsTimeseriesGet200ResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof StatsTimeseriesGet200ResponseDataInner
     */
    mean: number;
    /**
     * 
     * @type {number}
     * @memberof StatsTimeseriesGet200ResponseDataInner
     */
    variance: number;
}

/**
 * Check if a given object implements the StatsTimeseriesGet200ResponseDataInner interface.
 */
export function instanceOfStatsTimeseriesGet200ResponseDataInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "mean" in value;
    isInstance = isInstance && "variance" in value;

    return isInstance;
}

export function StatsTimeseriesGet200ResponseDataInnerFromJSON(json: any): StatsTimeseriesGet200ResponseDataInner {
    return StatsTimeseriesGet200ResponseDataInnerFromJSONTyped(json, false);
}

export function StatsTimeseriesGet200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatsTimeseriesGet200ResponseDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mean': json['mean'],
        'variance': json['variance'],
    };
}

export function StatsTimeseriesGet200ResponseDataInnerToJSON(value?: StatsTimeseriesGet200ResponseDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mean': value.mean,
        'variance': value.variance,
    };
}

