/* tslint:disable */
/* eslint-disable */
/**
 * Bactic
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Athlete } from './Athlete';
import {
    AthleteFromJSON,
    AthleteFromJSONTyped,
    AthleteToJSON,
} from './Athlete';

/**
 * 
 * @export
 * @interface TeamSummary
 */
export interface TeamSummary {
    /**
     * 
     * @type {string}
     * @memberof TeamSummary
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof TeamSummary
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TeamSummary
     */
    zscore?: number;
    /**
     * 
     * @type {Array<Athlete>}
     * @memberof TeamSummary
     */
    athletes?: Array<Athlete>;
}

/**
 * Check if a given object implements the TeamSummary interface.
 */
export function instanceOfTeamSummary(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function TeamSummaryFromJSON(json: any): TeamSummary {
    return TeamSummaryFromJSONTyped(json, false);
}

export function TeamSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
        'zscore': !exists(json, 'zscore') ? undefined : json['zscore'],
        'athletes': !exists(json, 'athletes') ? undefined : ((json['athletes'] as Array<any>).map(AthleteFromJSON)),
    };
}

export function TeamSummaryToJSON(value?: TeamSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'id': value.id,
        'zscore': value.zscore,
        'athletes': value.athletes === undefined ? undefined : ((value.athletes as Array<any>).map(AthleteToJSON)),
    };
}

