version: '3.9'

services:
  db:
    container_name: bactic_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=bactic
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgreqsl/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  scraper:
    container_name: bactic_scraper
    build:
      context: ../
      dockerfile: Dockerfile.scraper
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      - DB_URL=postgres://postgres:pass@bactic_db:5432/bactic?sslmode=disable
  stats:
    container_name: bactic_stats
    build:
      context: ../
      dockerfile: Dockerfile.stats
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      - DB_URL=postgres://postgres:pass@bactic_db:5432/bactic?sslmode=disable

  site:
    container_name: bactic_site
    build:
      context: ../
      dockerfile: Dockerfile.web
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db 
    environment:
      - DB_URL=postgres://postgres:pass@bactic_db:5432/bactic?sslmode=disable
    ports:
      - 8080:8080
volumes:
  db:
    driver: local
