version: '3.9'

services:
  db:
    container_name: bactic_db
    image: postgres
    restart: always
    env_file:
      - variables.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgreqsl/data

  backend:
    container_name: bactic_backend
    build: src/bactic-backend
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:pass@bactic_db:5432/bactic

  scraper:
    build: src/scraper
    depends_on:
      - db
      - backend
    env_file:
      - variables.env
volumes:
  db:
    driver: local