version: '3.9'

services:
  db:
    container_name: bactic_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=bactic
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgreqsl/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  scraper:
    container_name: bactic_scraper
    build:
      context: ../
      dockerfile: build/scraper/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      - DB_URI=postgres://postgres:pass@bactic_db:5432/bactic?sslmode=disable

  stats:
    container_name: bactic_stats
    build:
      context: ../
      dockerfile: build/stats/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
      stats-cache:
        condition: service_healthy
    links:
      - db
      - stats-cache
    environment:
      - DB_URI=postgres://postgres:pass@bactic_db:5432/bactic?sslmode=disable
      - CACHE_URI=redis://bactic_stats

  stats-cache:
    container_name: bactic_stats-cache
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  site:
    container_name: bactic_site
    build:
      context: ../
      dockerfile: build/web/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db 
    environment:
      - DB_URI=postgres://postgres:pass@bactic_db:5432/bactic?sslmode=disable
    ports:
      - 8080:8080
      
volumes:
  db:
    driver: local
