DROP TABLE IF EXISTS league;
DROP TABLE IF EXISTS result;
DROP TABLE IF EXISTS heat;
DROP TABLE IF EXISTS athlete_in_school;
DROP TABLE IF EXISTS athlete;
DROP TABLE IF EXISTS school;
DROP TABLE IF EXISTS meet;
DROP TABLE IF EXISTS athlete_map;
