version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=bactic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgreqsl/data
  backend:
    build: src/bactic-backend

volumes:
  db:
    driver: local

configs:
