version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=bactic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgreqsl/data
  volumes:
    db:
      driver: local