FROM python:alpine3.12

WORKDIR /usr/src/app

COPY stats/requirements.txt ./
RUN apk add --no-cache postgresql-libs && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 pip install -r requirements.txt --no-cache-dir && \
 apk --purge del .build-deps

COPY ./stats .

CMD [ "python", "." ]