/*
 * Bactic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"
)

// DefaultAPIRouter defines the required methods for binding the api requests to a responses for the DefaultAPI
// The DefaultAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultAPIServicer to perform the required actions, then write the service results to the http response.
type DefaultAPIRouter interface {
	SearchAthleteGet(http.ResponseWriter, *http.Request)
	StatsAthleteIdGet(http.ResponseWriter, *http.Request)
	StatsHistGet(http.ResponseWriter, *http.Request)
	StatsTeamIdGet(http.ResponseWriter, *http.Request)
	StatsTimeseriesGet(http.ResponseWriter, *http.Request)
}

// DefaultAPIServicer defines the api actions for the DefaultAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultAPIServicer interface {
	SearchAthleteGet(context.Context, string) (ImplResponse, error)
	StatsAthleteIdGet(context.Context, int64) (ImplResponse, error)
	StatsHistGet(context.Context, []Event, float32) (ImplResponse, error)
	StatsTeamIdGet(context.Context, int64) (ImplResponse, error)
	StatsTimeseriesGet(context.Context, string, string, int64) (ImplResponse, error)
}
