/*
 * Bactic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api




type Athlete struct {

	Name string `json:"name,omitempty"`

	Id int64 `json:"id,omitempty"`
}

// AssertAthleteRequired checks if the required fields are not zero-ed
func AssertAthleteRequired(obj Athlete) error {
	return nil
}

// AssertAthleteConstraints checks if the values respects the defined constraints
func AssertAthleteConstraints(obj Athlete) error {
	return nil
}
