/*
 * Bactic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api




type SearchItem struct {

	Name string `json:"name"`

	Id int64 `json:"id"`
}

// AssertSearchItemRequired checks if the required fields are not zero-ed
func AssertSearchItemRequired(obj SearchItem) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSearchItemConstraints checks if the values respects the defined constraints
func AssertSearchItemConstraints(obj SearchItem) error {
	return nil
}
