/*
 * Bactic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api




type AthleteSummary struct {

	Athlete Athlete `json:"athlete,omitempty"`

	Zscore float32 `json:"zscore,omitempty"`
}

// AssertAthleteSummaryRequired checks if the required fields are not zero-ed
func AssertAthleteSummaryRequired(obj AthleteSummary) error {
	if err := AssertAthleteRequired(obj.Athlete); err != nil {
		return err
	}
	return nil
}

// AssertAthleteSummaryConstraints checks if the values respects the defined constraints
func AssertAthleteSummaryConstraints(obj AthleteSummary) error {
	return nil
}
