/*
 * Bactic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"bactic/internal/api"
	"flag"
	"log"
	"net/http"
	"os"

	_ "github.com/lib/pq"
)

func main() {
	var (
		dbURI string
		found bool
	)
	flag.StringVar(&dbURI, "db", "", "Fully-qualified postgres url. Overrides the environment variable defined in DB_URL")
	flag.Parse()

	if len(dbURI) == 0 {
		dbURI, found = os.LookupEnv("DB_URI")
		if !found {
			log.Fatal("Database url not found in environment variable DB_URI. It must be specified in the arg \"db\"")
		}
	}

	APIServicer := api.NewAPIServicer(dbURI)
	APIRouter := api.NewAPIRouter(APIServicer)
	api.RegisterRoutes(APIRouter)
	log.Printf("Server started")
	log.Fatal(http.ListenAndServe(":8080", nil))
}
