/*
 * Bactic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"bactic/internal/api"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	DefaultAPIService := api.NewDefaultAPIService()
	DefaultAPIController := api.NewDefaultAPIController(DefaultAPIService)

	router := api.NewRouter(DefaultAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
