/*
 * Bactic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package internal

// ImplResponse defines an implementation response with error code and the associated body
type ImplResponse struct {
	Body interface{}
	Code int
}
