/*
 * Bactic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package internal

type StatsTimeseriesGet200ResponseDataInner struct {
	Mean float32 `json:"mean"`

	Variance float32 `json:"variance"`
}

// AssertStatsTimeseriesGet200ResponseDataInnerRequired checks if the required fields are not zero-ed
func AssertStatsTimeseriesGet200ResponseDataInnerRequired(obj StatsTimeseriesGet200ResponseDataInner) error {
	elements := map[string]interface{}{
		"mean":     obj.Mean,
		"variance": obj.Variance,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertStatsTimeseriesGet200ResponseDataInnerConstraints checks if the values respects the defined constraints
func AssertStatsTimeseriesGet200ResponseDataInnerConstraints(obj StatsTimeseriesGet200ResponseDataInner) error {
	return nil
}
