/*
 * Bactic
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package internal

type TeamSummary struct {
	Name     string    `json:"name"`
	Athletes []Athlete `json:"athletes,omitempty"`
	Id       uint32    `json:"id"`
	Zscore   float32   `json:"zscore,omitempty"`
}

// AssertTeamSummaryRequired checks if the required fields are not zero-ed
func AssertTeamSummaryRequired(obj TeamSummary) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"id":   obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Athletes {
		if err := AssertAthleteRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTeamSummaryConstraints checks if the values respects the defined constraints
func AssertTeamSummaryConstraints(obj TeamSummary) error {
	return nil
}
